runtime: nodejs18

env_variables:
  RUNRIDE_DB_URI: "mongodb+srv://movies-db-user:movies-db-user-123@cluster0.l4nctnv.mongodb.net/ride_run_db?retryWrites=true&w=majority"
  RUNRIDE_COLLECTION: "ride_run_db"